[tool.black]
line-length = 88
target-version = ["py36"]
include = '\.pyi?$'
exclude = '''

(
  /(
      \.git
    | venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
combine_as_imports = true
skip = [
    "venv",
]

[tool.pytest.ini_options]
norecursedirs = [
    "venv",
]
